// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAqt3HAd1Dz2bUTuSoIvF5H__CNTZAOvD4',
    appId: '1:487913960052:web:84aa6b274aec5930125721',
    messagingSenderId: '487913960052',
    projectId: 'ai-chef-recipe-generator',
    authDomain: 'ai-chef-recipe-generator.firebaseapp.com',
    storageBucket: 'ai-chef-recipe-generator.firebasestorage.app',
    measurementId: 'G-1X827DSKC4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCMZi2awgrlyNyRb3aHpwkBbP_5V3Ls-Wc',
    appId: '1:487913960052:android:e318198cc2e69c04125721',
    messagingSenderId: '487913960052',
    projectId: 'ai-chef-recipe-generator',
    storageBucket: 'ai-chef-recipe-generator.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDaFJRrk1qOeDpWVxtWUHcdQ5FmRJM3Wcw',
    appId: '1:487913960052:ios:480f202cb4d955af125721',
    messagingSenderId: '487913960052',
    projectId: 'ai-chef-recipe-generator',
    storageBucket: 'ai-chef-recipe-generator.firebasestorage.app',
    androidClientId: '487913960052-tck01mf3flmjvp60aqme13fn95ea6pop.apps.googleusercontent.com',
    iosClientId: '487913960052-do081ooj1bvf9husd3gvmffajddk4ep1.apps.googleusercontent.com',
    iosBundleId: 'com.example.recipeAiApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDaFJRrk1qOeDpWVxtWUHcdQ5FmRJM3Wcw',
    appId: '1:487913960052:ios:480f202cb4d955af125721',
    messagingSenderId: '487913960052',
    projectId: 'ai-chef-recipe-generator',
    storageBucket: 'ai-chef-recipe-generator.firebasestorage.app',
    androidClientId: '487913960052-tck01mf3flmjvp60aqme13fn95ea6pop.apps.googleusercontent.com',
    iosClientId: '487913960052-do081ooj1bvf9husd3gvmffajddk4ep1.apps.googleusercontent.com',
    iosBundleId: 'com.example.recipeAiApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAqt3HAd1Dz2bUTuSoIvF5H__CNTZAOvD4',
    appId: '1:487913960052:web:5f1e8164095cedfd125721',
    messagingSenderId: '487913960052',
    projectId: 'ai-chef-recipe-generator',
    authDomain: 'ai-chef-recipe-generator.firebaseapp.com',
    storageBucket: 'ai-chef-recipe-generator.firebasestorage.app',
    measurementId: 'G-7K1SVVFHWH',
  );
}
